{% set name = "bluesky-httpserver" %}
{% set version = "0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ecb94d4ce9b8afd9cb33ac190daa51881ba63c45a7f8bdb8a8080012edf57216

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - bluesky-queueserver
    - bluesky-queueserver-api
    - fastapi
    - python
    - pyzmq
    - requests
    - typing-extensions  # [py<38]
    - uvicorn

test:
  imports:
    - bluesky_httpserver
    - bluesky_httpserver.server
  requires:
    - pip

about:
  home: https://github.com/bluesky/bluesky-httpserver
  summary: HTTP Server for communicating with Bluesky Queue Server
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-httpserver
  dev_url: https://github.com/bluesky/bluesky-httpserver

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
