{% set name = "bluesky-httpserver" %}
{% set version = "0.0.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: b51f85fd5c43495fb92e9372a4a41b3870cdb907740de1e0a59fa251aca36254

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - alembic
    - bluesky-queueserver
    - bluesky-queueserver-api
    - fastapi
    - ldap3
    - orjson
    - pamela
    - pydantic-settings
    - python-jose
    - pyzmq
    - requests
    - sqlalchemy
    - starlette
    - uvicorn

test:
  imports:
    - bluesky_httpserver
    - bluesky_httpserver.server
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bluesky/bluesky-httpserver
  summary: HTTP Server for communicating with Bluesky Queue Server
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://blueskyproject.io/bluesky-httpserver
  dev_url: https://github.com/bluesky/bluesky-httpserver

extra:
  recipe-maintainers:
    - dmgav
    - mrakitin
